language: node_js
node_js:
  - 10

cache:
  npm: false
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install

script:
  - pnpm run build
  - pnpm install -g gh-pages
  - gh-pages --dist dist --dest exporter --repo https://x-access-token:${GITHUB_TOKEN}@github.com/MoonsideGames/moonsidegames.github.io.git --branch master
