language: node_js
node_js:
  - 10

cache:
  npm: false
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
  
script:
  - pnpm run build

# Deploy the site - this hook comes from Travis integration
deploy:
  # The output of our static site
  local_dir: dist
  # The repository we are deploying to
  repo: MoonsideGames/moonsidegames.github.io
  # The branch we are pushing the static repository
  target_branch: master
  # Information to use in the commit
  email: evan@moonside.games
  name: "Evan Hemsley"
  provider: pages
  # Recommended setting
  skip_cleanup: true
  # Set in Travis CI dashboard
  github_token: $GITHUB_TOKEN
  on:
    branch: master